<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- CONSTANTS -->
    <xacro:property name="pi" value="3.1415926535897931" />

    <!-- Multiplicative factor applied to the radius of the caster balls
         for them not to stop both wheels to be touching the ground at
         the same time                                               -->
    <xacro:property name="reduction_factor_caster_radius" value="0.998" />
    <!-- </CONSTANTS> -->

    <!-- PARAMETERS -->

    <!-- Base parameters -->
    <xacro:property name="base_radius" value="0.4" />
    <!-- base height must be inside (wheel_radius, 2*wheel_radius) -->
    <!-- note that the extremes of the interval are not included   -->
    <xacro:property name="base_height" value="0.15" />
    <xacro:property name="base_mass" value="15.0" />

    <!-- Wheel parameters -->
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="wheel_mass" value="5.0" />

    <xacro:property name="z_offset_between_centers" value="${wheel_radius - base_height/2}" />

    <!-- Sensor's base parameters -->
    <xacro:property name="sensors_base_heigth" value="${(2*wheel_radius - base_height)/2}" />
    <xacro:property name="sensors_base_mass" value="5.0" />
    <xacro:property name="sensors_base_offset_z" value="${base_height/2 + sensors_base_heigth/2}" />
    <!-- </PARAMETERS> -->

    <!-- MACROS -->

    <!-- Inertial of a cylinder -->
    <xacro:macro name="cylinder_inertial" params="mass radius length">
        <inertial>
            <mass value="${mass}" />
            <inertia
                ixx="${1/12*mass*(3*radius*radius + length*length)}" ixy="0" ixz="0"
                iyy="${1/12*mass*(3*radius*radius + length*length)}" iyz="0"
                izz="${1/2*mass*radius*radius}"
            />
        </inertial>
    </xacro:macro>

    <!-- Add a wheel and its joint on the x axis, outer part of the base -->
    <xacro:macro name="wheel" params="side reflect">
        <link name="${side}_wheel">
            <xacro:cylinder_inertial
                mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}"
            />

            <collision name="${side}_wheel_collision">
                <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>

            <visual name="${side}_wheel_visual">
                <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </visual>
        </link>

        <joint type="continuous" name="${side}_wheel_hinge">
            <origin
                xyz="0 ${reflect*(base_radius + wheel_length/2)} ${-z_offset_between_centers}"
                rpy="0 0 0"
            />
            <child link="${side}_wheel"/>
            <parent link="base"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <limit effort="10000" velocity="1000"/>
            <dynamics damping="1.0" friction="1.0"/>
        </joint>
    </xacro:macro>
    <!-- </MACROS> -->



    <!-- ROBOT DESCRIPTION-->
    <link name="robot_footprint"></link>

    <joint name="robot_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="robot_footprint"/>
        <child link="base"/>
    </joint>

    <!-- Cylindrical base with two casters for stability along the y axis-->
    <link name="base">
        <!-- we want the wheel to touch the ground and the top of the base
             to coincide with the top of the wheel                       -->
        <pose>0 0 ${wheel_radius + z_offset_between_centers} 0 0 0</pose>

        <xacro:cylinder_inertial
            mass="${base_mass}" radius="${base_radius}" length="${base_height}"
        />

        <collision name="base_collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}" />
            </geometry>
        </collision>

        <visual name="base_visual">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}" />
            </geometry>
        </visual>

        <collision name="back_caster_collision">
            <origin
                xyz="${-3/4*base_radius} 0 ${-wheel_radius/2 - z_offset_between_centers}"
                rpy="0 0 0"
            />
            <geometry>
                <sphere radius="${reduction_factor_caster_radius*wheel_radius/2}"/>
            </geometry>
        </collision>

        <visual name="back_caster_visual">
            <origin
                xyz="${-3/4*base_radius} 0 ${-wheel_radius/2 - z_offset_between_centers}"
                rpy="0 0 0"
            />
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </visual>

        <collision name="front_caster_collision">
            <origin
                xyz="${3/4*base_radius} 0 ${-wheel_radius/2 - z_offset_between_centers}"
                rpy="0 0 0"
            />
            <geometry>
                <sphere radius="${reduction_factor_caster_radius*wheel_radius/2}"/>
            </geometry>
        </collision>

        <visual name="front_caster_visual">
            <origin
                xyz="${3/4*base_radius} 0 ${-wheel_radius/2 - z_offset_between_centers}"
                rpy="0 0 0"
            />
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </visual>

    </link>

    <!-- Wheels on the x axis with their corresponding joints -->
    <xacro:wheel side="left" reflect="-1" />
    <xacro:wheel side="right" reflect="1" />

    <!-- Rotating base for the sensors -->
    <link name="sensors_base">
        <xacro:cylinder_inertial
            mass="${sensors_base_mass}" radius="${base_radius}" length="${sensors_base_heigth}"
        />

        <collision name="sensors_base_collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${sensors_base_heigth}" />
            </geometry>
        </collision>

        <visual name="sensors_base_visual">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${sensors_base_heigth}" />
            </geometry>
        </visual>
    </link>

    <joint name="sensors_base_hinge" type="continuous">
        <origin xyz="0 0 ${sensors_base_offset_z}" rpy="0 0 0" />
        <child link="sensors_base" />
        <parent link="base" />
        <axis xyz="0 0 1" rpy="0 0 0" />
        <limit effort="10000" velocity="1000" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <!-- </ROBOT DESCRIPTION> -->

</robot>